# TCL File Generated by Component Editor 18.1
# Wed Feb 28 13:45:41 CET 2024
# DO NOT MODIFY


# 
# ip_8b10b_decoder "8b/10b Decoder (ip_mu3e)" v1.3
# Yifeng Wang 2024.02.28.13:45:41
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ip_8b10b_decoder
# 
set_module_property DESCRIPTION ""
set_module_property NAME ip_8b10b_decoder
set_module_property VERSION 1.3.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Mu3e Data Plane/Modules"
set_module_property AUTHOR "Yifeng Wang"
set_module_property DISPLAY_NAME "8b/10b Decoder (ip_mu3e)"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dec_8b10b_n
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dec_8b10b.vhd VHDL PATH dec_8b10b.vhd
add_fileset_file dec_8b10b_n.vhd VHDL PATH dec_8b10b_n.vhd TOP_LEVEL_FILE
add_fileset_file util_pkg.vhd VHDL PATH util_pkg.vhd


# 
# parameters
# 
add_parameter FLIP_10B BOOLEAN true
set_parameter_property FLIP_10B DEFAULT_VALUE true
set_parameter_property FLIP_10B DISPLAY_NAME FLIP_10B
set_parameter_property FLIP_10B TYPE BOOLEAN
set_parameter_property FLIP_10B UNITS None
set_parameter_property FLIP_10B HDL_PARAMETER true
add_parameter CHANNEL_WIDTH NATURAL 3 ""
set_parameter_property CHANNEL_WIDTH DEFAULT_VALUE 3
set_parameter_property CHANNEL_WIDTH DISPLAY_NAME CHANNEL_WIDTH
set_parameter_property CHANNEL_WIDTH TYPE NATURAL
set_parameter_property CHANNEL_WIDTH UNITS None
set_parameter_property CHANNEL_WIDTH ALLOWED_RANGES 0:2147483647
set_parameter_property CHANNEL_WIDTH DESCRIPTION ""
set_parameter_property CHANNEL_WIDTH HDL_PARAMETER true
add_parameter g_BYTES POSITIVE 1
set_parameter_property g_BYTES DEFAULT_VALUE 1
set_parameter_property g_BYTES DISPLAY_NAME g_BYTES
set_parameter_property g_BYTES TYPE POSITIVE
set_parameter_property g_BYTES UNITS None
set_parameter_property g_BYTES ALLOWED_RANGES 1:2147483647
set_parameter_property g_BYTES HDL_PARAMETER true



#
# callback
#
set_module_property ELABORATION_CALLBACK elaborate

proc elaborate {} {
	set width [get_parameter_value CHANNEL_WIDTH]
	set max_channel [expr 2**$width-1]
	send_message INFO [format "Set the max_channel (%s) attribute according the channel width" $max_channel]
	set_interface_property in10b maxChannel $max_channel
	set_interface_property out8b maxChannel $max_channel
}




# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink i_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock ""
set_interface_property reset_sink synchronousEdges NONE
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink i_reset_n reset_n Input 1


# 
# connection point in10b
# 
add_interface in10b avalon_streaming end
set_interface_property in10b associatedClock clock_sink
set_interface_property in10b associatedReset reset_sink
set_interface_property in10b dataBitsPerSymbol 10
set_interface_property in10b errorDescriptor lane_training_failure
set_interface_property in10b firstSymbolInHighOrderBits true
set_interface_property in10b maxChannel 0
set_interface_property in10b readyLatency 0
set_interface_property in10b ENABLED true
set_interface_property in10b EXPORT_OF ""
set_interface_property in10b PORT_NAME_MAP ""
set_interface_property in10b CMSIS_SVD_VARIABLES ""
set_interface_property in10b SVD_ADDRESS_GROUP ""

add_interface_port in10b asi_in10b_data data Input 10
add_interface_port in10b asi_in10b_valid valid Input 1
add_interface_port in10b asi_in10b_channel channel Input channel_width
add_interface_port in10b asi_in10b_error error Input 1


# 
# connection point out8b
# 
add_interface out8b avalon_streaming start
set_interface_property out8b associatedClock clock_sink
set_interface_property out8b associatedReset reset_sink
set_interface_property out8b dataBitsPerSymbol 9
set_interface_property out8b errorDescriptor ""
set_interface_property out8b firstSymbolInHighOrderBits true
set_interface_property out8b maxChannel 0
set_interface_property out8b readyLatency 0
set_interface_property out8b ENABLED true
set_interface_property out8b EXPORT_OF ""
set_interface_property out8b PORT_NAME_MAP ""
set_interface_property out8b CMSIS_SVD_VARIABLES ""
set_interface_property out8b SVD_ADDRESS_GROUP ""

add_interface_port out8b aso_out8b_data data Output 9
add_interface_port out8b aso_out8b_valid valid Output 1
add_interface_port out8b aso_out8b_channel channel Output channel_width
add_interface_port out8b aso_out8b_error error Output 3

